version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: edunova-db
    restart: always
    environment:
      MYSQL_DATABASE: edunova_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: edunova-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/edunova_db?useSSL=false&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

volumes:
  mysql_data:
